### ISSUE TITLE
Implement default settings for database connections

### ISSUE THREAD

**Issue by jackson-nestelroad** [datajoint/datajoint-core#3]
Define and implement a unified set of settings (along with their defaults) for connecting to MySQL and Postgres databases. datajoint-core should currently only use default settings, but setting these settings programmatically and reading them from a file should also be supported. All settings should be appropriately mapped to SQLx for creating a database connection.

**Comment by jonathanschroeter** [comment]
Closed by merge request on 10/1/2021 #12
